### ISSUE TITLE
Firestore Database access.

### ISSUE THREAD

**Issue by Andrik7289** [kartixharma/Convoix#1]
Hey, man, can you please send structure of your Firestore database, that stores all messages, stories and other data that you are using on your app. I am making project on Android and want to take some features from your cool chat. Thanks!

**Comment by kartixharma** [comment]
> Hey, man, can you please send structure of your Firestore database, that stores all messages, stories and other data that you are using on your app. I am making project on Android and want to take some features from your cool chat. Thanks!

You can refer Datatypes.kt file for that..

**Comment by Andrik7289** [comment]
Thanks!
